In [1]:
! pip install scikit-learn

In [2]:
import numpy as np
from sklearn.datasets import make_classification
from sklearn.model_selection import train_test_split

In [3]:
#Creating the DataSet
data = make_classification(n_samples=10, n_features=2, n_informative=2, n_redundant=0, n_classes=2, random_state=42)

In [4]:
data

(array([[ 1.06833894, -0.97007347],
        [-1.14021544, -0.83879234],
        [-2.8953973 ,  1.97686236],
        [-0.72063436, -0.96059253],
        [-1.96287438, -0.99225135],
        [-0.9382051 , -0.54304815],
        [ 1.72725924, -1.18582677],
        [ 1.77736657,  1.51157598],
        [ 1.89969252,  0.83444483],
        [-0.58723065, -1.97171753]]),
 array([1, 0, 0, 0, 0, 1, 1, 1, 1, 0]))

In [5]:
type(data)

tuple

In [6]:
len(data)

2

In [6]:
X = data[0]

In [9]:
type(X)

numpy.ndarray

In [11]:
X.shape

(10, 2)

In [10]:
y = data[1]

In [11]:
y

array([1, 0, 0, 0, 0, 1, 1, 1, 1, 0])

In [12]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [13]:
data

(array([[ 1.06833894, -0.97007347],
        [-1.14021544, -0.83879234],
        [-2.8953973 ,  1.97686236],
        [-0.72063436, -0.96059253],
        [-1.96287438, -0.99225135],
        [-0.9382051 , -0.54304815],
        [ 1.72725924, -1.18582677],
        [ 1.77736657,  1.51157598],
        [ 1.89969252,  0.83444483],
        [-0.58723065, -1.97171753]]),
 array([1, 0, 0, 0, 0, 1, 1, 1, 1, 0]))

In [15]:
X_train

array([[-0.9382051 , -0.54304815],
       [ 1.06833894, -0.97007347],
       [ 1.77736657,  1.51157598],
       [-2.8953973 ,  1.97686236],
       [-0.58723065, -1.97171753],
       [-1.96287438, -0.99225135],
       [-0.72063436, -0.96059253],
       [ 1.72725924, -1.18582677]])

In [16]:
#Data Normalization
from sklearn.preprocessing import MinMaxScaler
sc = MinMaxScaler()

In [17]:
sc.fit(X_train)

MinMaxScaler()

In [18]:
X_trained = sc.transform(X_train)

In [26]:
X_trained, X_train

(array([[0.41885108, 0.36181853],
        [0.84826376, 0.25367198],
        [1.        , 0.88216362],
        [0.        , 1.        ],
        [0.49396176, 0.        ],
        [0.1995656 , 0.2480553 ],
        [0.46541255, 0.25607308],
        [0.98927673, 0.19903124]]),
 array([[-0.9382051 , -0.54304815],
        [ 1.06833894, -0.97007347],
        [ 1.77736657,  1.51157598],
        [-2.8953973 ,  1.97686236],
        [-0.58723065, -1.97171753],
        [-1.96287438, -0.99225135],
        [-0.72063436, -0.96059253],
        [ 1.72725924, -1.18582677]]))

In [28]:
X_trained.min()

0.0

In [29]:
X_trained_2 = sc.fit_transform(X_train)

In [30]:
X_trained_2

array([[0.41885108, 0.36181853],
       [0.84826376, 0.25367198],
       [1.        , 0.88216362],
       [0.        , 1.        ],
       [0.49396176, 0.        ],
       [0.1995656 , 0.2480553 ],
       [0.46541255, 0.25607308],
       [0.98927673, 0.19903124]])